version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: laravel-api
    working_dir: /var/www
    volumes:
      - ./laravel-api:/var/www
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=laravel
      - ELASTICSEARCH_HOST=http://elasticsearch:9200
    expose:
      - "9000"
    depends_on:
      - mysql
      - elasticsearch
    networks:
      - devnet

  nginx:
    image: nginx:stable
    container_name: nginx-controller
    ports:
      - "81:80"
    volumes:
      - ./laravel-api:/var/www
      - ./nginx-controller/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - devnet

  react:
    image: node:24
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react-frontend:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - app
    networks:
      - devnet
    command: sh -c "npm install && npm run dev"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - devnet

  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - devnet

networks:
  devnet:

volumes:
  dbdata:
